# Generated by Django 4.2.6 on 2023-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('normal', 'Normal')], default='normal', max_length=25)),
                ('status', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('normal', 'Normal')], default='pendente', max_length=25)),
            ],
        ),
    ]
